<<<<<<< Updated upstream
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
=======
/* eslint-disable @next/next/no-img-element */
import Layout from '@/components/Layout';
import ProductCard from '@/components/ProductCard';
import { useEffect, useState } from 'react';
import SwiperCore, { Navigation, Pagination, Autoplay } from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/swiper-bundle.min.css';
import { fetchError } from '@/components/Common';
import Axios from 'axios';
import { useRouter } from 'next/router';
>>>>>>> Stashed changes

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
<<<<<<< Updated upstream
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>
=======
    const [email, setEmail] = useState('');
    const [allProduct, setAllProduct] = useState([]);
    const [ethnicProduct, setEthnicProduct] = useState([]);
    const [veganProduct, setVeganProduct] = useState([]);
    const [gourmetProduct, setGourmetProduct] = useState([]);
    const router = useRouter();
>>>>>>> Stashed changes

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

<<<<<<< Updated upstream
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
=======
            {/* Ethnic Foods */}
            <div className="mx-20 my-12 product-swiper">
                <div className="flex justify-between mb-6">
                    <h1 className="card-title">Ethnic Foods </h1>
                    <button className="card-button" onClick={() => router.push('/shop')}>
                        SEE ALL
                    </button>
                </div>

                <Swiper slidesPerView={5} spaceBetween={60}>
                    {ethnicProduct.map((product) => (
                        <SwiperSlide key={product._id}>
                            <ProductCard product={product} />
                        </SwiperSlide>
                    ))}
                </Swiper>
            </div>

            {/* Vegan Foods */}
            <div className="mx-20 my-12 product-swiper">
                <div className="flex justify-between mb-6">
                    <h1 className="card-title">Vegan Foods </h1>
                    <button className="card-button" onClick={() => router.push('/shop')}>
                        SEE ALL
                    </button>
                </div>

                <Swiper slidesPerView={5} spaceBetween={60}>
                    {veganProduct.map((product) => (
                        <SwiperSlide key={product._id}>
                            <ProductCard product={product} />
                        </SwiperSlide>
                    ))}
                </Swiper>
            </div>

            {/* Gourmet Foods */}
            <div className="mx-20 my-12 product-swiper">
                <div className="flex justify-between mb-6">
                    <h1 className="card-title">Gourmet Foods</h1>
                    <button className="card-button" onClick={() => router.push('/shop')}>
                        SEE ALL
                    </button>
                </div>

                <Swiper slidesPerView={5} spaceBetween={60}>
                    {gourmetProduct.map((product) => (
                        <SwiperSlide key={product._id}>
                            <ProductCard product={product} />
                        </SwiperSlide>
                    ))}
                </Swiper>
            </div>

            <div className="bg-fixed bg-cover bg-center h-80" style={{ backgroundImage: "url('/subscribe-background.jpg')" }}>
                <div className="flex justify-between items-center h-full mx-20">
                    <h1 className="text-4xl font-medium text-white">SUBSCRIBE TO OUR NEWSLETTER</h1>
                    <div className="flex items-center">
                        <input
                            type="text"
                            placeholder="YOUR EMAIL ADDRESS"
                            className="bg-white px-8 py-4 rounded-lg shadow-lg focus:ring-2 focus:ring-zinc-800 outline-none border-transparent"
                            onChange={(event) => {
                                setEmail(event.target.value);
                            }}
                        />
                        <button className="btn-subscribe" onClick={subscribeHandle}>
                            SUBSCRIBE
                        </button>
                    </div>
                </div>
            </div>
        </Layout>
    );
>>>>>>> Stashed changes
}
