apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
      - name: rating
        image: fazidsamoon/ds-rating
        env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: mongo-uri
                key: MONGO_URI
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret-key
                key: JWT_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: rating-srv
spec:
  selector:
    app: rating
  ports:
    - name: rating
      protocol: TCP
      port: 3004
      targetPort: 3004